// Compiles wasm/kernels.ts with AssemblyScript and writes src/wasm/kernels.js,
// which embeds the binary so that the library needs no separate file or fetch.
// Run: npm run build-wasm
import { Buffer } from 'node:buffer';
import { writeFile } from 'node:fs/promises';
import process from 'node:process';

import asc from 'assemblyscript/asc';

const outputs = {};
const { error, stderr } = await asc.main(
  [
    'wasm/kernels.ts',
    '--enable',
    'simd',
    '--optimizeLevel',
    '3',
    '--shrinkLevel',
    '0',
    '--runtime',
    'stub',
    '--noAssert',
    '--use',
    'abort=',
    // src/wasm/index.js gives each instance a memory of the size it needs,
    // never growing one (see Kernels there).
    '--importMemory',
    '--outFile',
    'kernels.wasm',
  ],
  {
    writeFile(name, contents) {
      outputs[name] = contents;
    },
  },
);
if (error) {
  process.stderr.write(stderr.toString());
  throw error;
}

const bytes = Buffer.from(outputs['kernels.wasm']);
const lines = bytes
  .toString('base64')
  .match(/.{1,76}/g)
  .map((line) => `  '${line}'`);
await writeFile(
  new URL('../src/wasm/kernels.js', import.meta.url),
  `// Generated by tools/buildWasm.mjs from wasm/kernels.ts. Do not edit.
// ${bytes.length} bytes of WebAssembly (with SIMD), base64-encoded.
export const kernels =
${lines.join(' +\n')};
`,
);
process.stdout.write(
  `src/wasm/kernels.js: ${bytes.length} bytes of WebAssembly\n`,
);
